import { createFileRoute, Link } from "@tanstack/react-router";
import { LegalPage, legalHead } from "@/components/legal-page";
import { SITE } from "@/lib/site";

export const Route = createFileRoute("/terms")({
  staticData: { sitemap: true },
  head: () =>
    legalHead(
      "Terms of service",
      "The agreement that governs your use of REACHER AI: accounts, AI-generated output, published reports, sponsors, acceptable use, and liability.",
      "/terms",
    ),
  component: TermsPage,
});

function TermsPage() {
  const operator = SITE.legalEntity || SITE.operator;
  return (
    <LegalPage
      eyebrow="legal"
      title="Terms of service"
      intro={`These terms are a contract between you and ${operator} ("we", "us") for the use of ${SITE.name} at ${SITE.origin}. By creating a workspace or using the service you accept them. If you use the service on behalf of a company, you confirm you are allowed to bind that company.`}
      sections={[
        {
          id: "service",
          heading: "What the service is",
          body: (
            <>
              <p>
                {SITE.name} is a web application in which a coordinated set of AI agents plans marketing
                work, researches topics using live web search, drafts content, and produces research
                reports. Reports show the sources used, a self-assessed quality score, and the compute
                the run consumed.
              </p>
              <p>
                The service is provided free of charge to workspace users. It is funded by clearly
                labelled sponsor placements on public report pages, described in section 6 and in our{" "}
                <Link to="/advertise" className="underline underline-offset-4">
                  sponsor disclosure
                </Link>
                .
              </p>
            </>
          ),
        },
        {
          id: "accounts",
          heading: "Accounts and workspaces",
          body: (
            <>
              <p>
                You need an account to use the service. You may sign up with an email address and
                password or with a Google account. You must be at least 16 years old and provide
                accurate information. You are responsible for keeping your credentials confidential and
                for all activity in your account.
              </p>
              <p>
                Each account gets a workspace. Workspace owners and admins may invite other people;
                invited members can see and edit the workspace's brands, conversations, documents,
                campaigns, and research. Do not invite anyone you would not trust with that material.
              </p>
              <p>
                You can delete your account at any time from Settings. Workspaces where you are the
                only member are deleted with all their content. In shared workspaces, conversations and
                library items you created are removed; brands, campaigns and research projects remain
                available to the remaining members with your name detached.
              </p>
            </>
          ),
        },
        {
          id: "ai-output",
          heading: "AI-generated output",
          body: (
            <>
              <p>
                Everything the agents produce is generated by large language models working from web
                pages retrieved during the run and from material you provided. Output can be wrong,
                incomplete, out of date, or biased, and a citation shows where a claim came from, not
                that the claim is true. You are responsible for reviewing output before you rely on it,
                publish it, or send it to anyone.
              </p>
              <p>
                The critic score is the model's own assessment of the report against its sources. It is
                not a guarantee of accuracy or a professional opinion. Nothing in the service is legal,
                financial, medical, or other professional advice.
              </p>
              <p>
                Web pages are fetched from third-party sites you do not control and we do not control.
                Their content belongs to their owners and is subject to their terms.
              </p>
            </>
          ),
        },
        {
          id: "your-content",
          heading: "Your content and our licence to it",
          body: (
            <>
              <p>
                You keep all rights in the prompts, brand material, documents, and other content you
                put into the service ("your content") and, to the extent we hold any, in the output
                generated for you. You grant us a worldwide, non-exclusive licence to host, store,
                process, and transmit your content solely to run the service for you and your
                workspace members.
              </p>
              <p>
                You confirm you have the rights needed to upload your content, including brand
                guidelines and documents from your employer or clients.
              </p>
            </>
          ),
        },
        {
          id: "publishing",
          heading: "Publishing reports",
          body: (
            <>
              <p>
                Research reports are private to your workspace until you turn on sharing. When you do,
                the report, its sources, its critic score and its run statistics are published at a
                public address under {SITE.origin}/r/ and may be indexed by search engines, listed in
                our sitemap, and cited by AI answer engines. You can turn sharing off at any time,
                after which the page returns "not found"; copies already made by third parties are
                outside our control.
              </p>
              <p>
                By publishing you grant us and every reader a non-exclusive licence to view, link to,
                quote with attribution, and cache the public page. You are responsible for making sure
                a published report does not contain confidential information, personal data of others,
                or unlawful content.
              </p>
            </>
          ),
        },
        {
          id: "sponsors",
          heading: "Sponsors",
          body: (
            <>
              <p>
                Public report pages may carry one clearly labelled sponsor card next to, never inside,
                the findings. Sponsors cannot see, edit, or influence a report's sources, wording, or
                conclusions. Sponsors receive aggregate impression and click counts only; they never
                receive information about readers or workspace users.
              </p>
              <p>
                Before certain research runs you may be offered a sponsored run. Accepting upgrades
                that project to the deepest research setting. Declining has no effect on your access
                to the service.
              </p>
            </>
          ),
        },
        {
          id: "acceptable-use",
          heading: "Acceptable use",
          body: (
            <p>
              You must follow our{" "}
              <Link to="/acceptable-use" className="underline underline-offset-4">
                acceptable use policy
              </Link>
              . In short: no unlawful, infringing, deceptive, or harmful use; no attempts to extract
              credentials, bypass limits, or interfere with the service; no use of the agents to
              harass, defame, or impersonate anyone. We may suspend or terminate accounts that break
              these rules.
            </p>
          ),
        },
        {
          id: "limits",
          heading: "Fair use limits and availability",
          body: (
            <>
              <p>
                To keep the service free, every workspace has monthly allowances for generated content
                and research runs and per-minute rate limits. Limits are enforced on our servers and
                shown in Settings. We may change allowances with notice inside the application.
              </p>
              <p>
                We aim for high availability but the service is provided "as is" and "as available".
                Live web search, model providers, and hosting are operated by third parties and can be
                unavailable; when that happens a run fails visibly rather than producing an unsourced
                report.
              </p>
            </>
          ),
        },
        {
          id: "liability",
          heading: "Warranties and liability",
          body: (
            <>
              <p>
                To the fullest extent permitted by law we exclude all implied warranties, including
                accuracy, fitness for a particular purpose, and non-infringement. We are not liable for
                indirect, consequential, or special loss, loss of profit, or loss of data arising from
                the service or from reliance on its output.
              </p>
              <p>
                Because the service is free, our total liability to you for any claim is limited to
                one hundred US dollars or the minimum permitted by applicable law, whichever is higher.
                Nothing in these terms limits liability that cannot be limited by law, including for
                fraud or for death or personal injury caused by negligence.
              </p>
            </>
          ),
        },
        {
          id: "termination",
          heading: "Suspension and termination",
          body: (
            <p>
              You may stop using the service and delete your account at any time. We may suspend or
              close accounts that breach these terms or create legal or security risk, and we may
              withdraw the service with reasonable notice. Sections on your content, publishing,
              liability, and governing law survive termination.
            </p>
          ),
        },
        {
          id: "changes",
          heading: "Changes to these terms",
          body: (
            <p>
              We may update these terms. Material changes are announced inside the application before
              they take effect, and the date at the top of this page changes. Continued use after that
              date means you accept the updated terms.
            </p>
          ),
        },
        {
          id: "law",
          heading: "Governing law and contact",
          body: (
            <>
              <p>
                {SITE.jurisdiction
                  ? `These terms are governed by the laws of ${SITE.jurisdiction}, and its courts have exclusive jurisdiction, without prejudice to mandatory consumer protections where you live.`
                  : "The governing law and venue for these terms will be stated here once the operator's registered details are published; until then, mandatory consumer protections where you live apply."}
              </p>
              <p>
                Questions about these terms:{" "}
                <Link to="/contact" className="underline underline-offset-4">
                  contact us
                </Link>{" "}
                and choose "Legal".
                {SITE.legalAddress ? ` Registered address: ${SITE.legalAddress}.` : ""}
              </p>
            </>
          ),
        },
      ]}
    />
  );
}
