/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppSponsorsRouteImport } from './routes/app.sponsors'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppKnowledgeRouteImport } from './routes/app.knowledge'
import { Route as AppContentRouteImport } from './routes/app.content'
import { Route as AppCampaignsRouteImport } from './routes/app.campaigns'
import { Route as AppBrandsRouteImport } from './routes/app.brands'
import { Route as AppArtifactsRouteImport } from './routes/app.artifacts'
import { Route as ApiResearchRouteImport } from './routes/api/research'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppResearchIndexRouteImport } from './routes/app.research.index'
import { Route as AppResearchProjectIdRouteImport } from './routes/app.research.$projectId'
import { Route as AppCConversationIdRouteImport } from './routes/app.c.$conversationId'
import { Route as ApiPublicCitationSweepRouteImport } from './routes/api/public/citation-sweep'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSponsorsRoute = AppSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppContentRoute = AppContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsRoute = AppBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AppRoute,
} as any)
const AppArtifactsRoute = AppArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => AppRoute,
} as any)
const ApiResearchRoute = ApiResearchRouteImport.update({
  id: '/api/research',
  path: '/api/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppResearchIndexRoute = AppResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchProjectIdRoute = AppResearchProjectIdRouteImport.update({
  id: '/research/$projectId',
  path: '/research/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppCConversationIdRoute = AppCConversationIdRouteImport.update({
  id: '/c/$conversationId',
  path: '/c/$conversationId',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicCitationSweepRoute = ApiPublicCitationSweepRouteImport.update({
  id: '/api/public/citation-sweep',
  path: '/api/public/citation-sweep',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/chat': typeof ApiChatRoute
  '/api/research': typeof ApiResearchRoute
  '/app/artifacts': typeof AppArtifactsRoute
  '/app/brands': typeof AppBrandsRoute
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/content': typeof AppContentRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sponsors': typeof AppSponsorsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/r/$slug': typeof RSlugRoute
  '/app/': typeof AppIndexRoute
  '/api/public/citation-sweep': typeof ApiPublicCitationSweepRoute
  '/app/c/$conversationId': typeof AppCConversationIdRoute
  '/app/research/$projectId': typeof AppResearchProjectIdRoute
  '/app/research/': typeof AppResearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/chat': typeof ApiChatRoute
  '/api/research': typeof ApiResearchRoute
  '/app/artifacts': typeof AppArtifactsRoute
  '/app/brands': typeof AppBrandsRoute
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/content': typeof AppContentRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sponsors': typeof AppSponsorsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/r/$slug': typeof RSlugRoute
  '/app': typeof AppIndexRoute
  '/api/public/citation-sweep': typeof ApiPublicCitationSweepRoute
  '/app/c/$conversationId': typeof AppCConversationIdRoute
  '/app/research/$projectId': typeof AppResearchProjectIdRoute
  '/app/research': typeof AppResearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/chat': typeof ApiChatRoute
  '/api/research': typeof ApiResearchRoute
  '/app/artifacts': typeof AppArtifactsRoute
  '/app/brands': typeof AppBrandsRoute
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/content': typeof AppContentRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sponsors': typeof AppSponsorsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/r/$slug': typeof RSlugRoute
  '/app/': typeof AppIndexRoute
  '/api/public/citation-sweep': typeof ApiPublicCitationSweepRoute
  '/app/c/$conversationId': typeof AppCConversationIdRoute
  '/app/research/$projectId': typeof AppResearchProjectIdRoute
  '/app/research/': typeof AppResearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/api/chat'
    | '/api/research'
    | '/app/artifacts'
    | '/app/brands'
    | '/app/campaigns'
    | '/app/content'
    | '/app/knowledge'
    | '/app/settings'
    | '/app/sponsors'
    | '/invite/$token'
    | '/r/$slug'
    | '/app/'
    | '/api/public/citation-sweep'
    | '/app/c/$conversationId'
    | '/app/research/$projectId'
    | '/app/research/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/api/chat'
    | '/api/research'
    | '/app/artifacts'
    | '/app/brands'
    | '/app/campaigns'
    | '/app/content'
    | '/app/knowledge'
    | '/app/settings'
    | '/app/sponsors'
    | '/invite/$token'
    | '/r/$slug'
    | '/app'
    | '/api/public/citation-sweep'
    | '/app/c/$conversationId'
    | '/app/research/$projectId'
    | '/app/research'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/api/chat'
    | '/api/research'
    | '/app/artifacts'
    | '/app/brands'
    | '/app/campaigns'
    | '/app/content'
    | '/app/knowledge'
    | '/app/settings'
    | '/app/sponsors'
    | '/invite/$token'
    | '/r/$slug'
    | '/app/'
    | '/api/public/citation-sweep'
    | '/app/c/$conversationId'
    | '/app/research/$projectId'
    | '/app/research/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiResearchRoute: typeof ApiResearchRoute
  InviteTokenRoute: typeof InviteTokenRoute
  RSlugRoute: typeof RSlugRoute
  ApiPublicCitationSweepRoute: typeof ApiPublicCitationSweepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sponsors': {
      id: '/app/sponsors'
      path: '/sponsors'
      fullPath: '/app/sponsors'
      preLoaderRoute: typeof AppSponsorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/content': {
      id: '/app/content'
      path: '/content'
      fullPath: '/app/content'
      preLoaderRoute: typeof AppContentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns': {
      id: '/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/brands': {
      id: '/app/brands'
      path: '/brands'
      fullPath: '/app/brands'
      preLoaderRoute: typeof AppBrandsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/artifacts': {
      id: '/app/artifacts'
      path: '/artifacts'
      fullPath: '/app/artifacts'
      preLoaderRoute: typeof AppArtifactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/research': {
      id: '/api/research'
      path: '/api/research'
      fullPath: '/api/research'
      preLoaderRoute: typeof ApiResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/research/': {
      id: '/app/research/'
      path: '/research'
      fullPath: '/app/research/'
      preLoaderRoute: typeof AppResearchIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/research/$projectId': {
      id: '/app/research/$projectId'
      path: '/research/$projectId'
      fullPath: '/app/research/$projectId'
      preLoaderRoute: typeof AppResearchProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/c/$conversationId': {
      id: '/app/c/$conversationId'
      path: '/c/$conversationId'
      fullPath: '/app/c/$conversationId'
      preLoaderRoute: typeof AppCConversationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/citation-sweep': {
      id: '/api/public/citation-sweep'
      path: '/api/public/citation-sweep'
      fullPath: '/api/public/citation-sweep'
      preLoaderRoute: typeof ApiPublicCitationSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppArtifactsRoute: typeof AppArtifactsRoute
  AppBrandsRoute: typeof AppBrandsRoute
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppContentRoute: typeof AppContentRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSponsorsRoute: typeof AppSponsorsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCConversationIdRoute: typeof AppCConversationIdRoute
  AppResearchProjectIdRoute: typeof AppResearchProjectIdRoute
  AppResearchIndexRoute: typeof AppResearchIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArtifactsRoute: AppArtifactsRoute,
  AppBrandsRoute: AppBrandsRoute,
  AppCampaignsRoute: AppCampaignsRoute,
  AppContentRoute: AppContentRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSponsorsRoute: AppSponsorsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCConversationIdRoute: AppCConversationIdRoute,
  AppResearchProjectIdRoute: AppResearchProjectIdRoute,
  AppResearchIndexRoute: AppResearchIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
  ApiResearchRoute: ApiResearchRoute,
  InviteTokenRoute: InviteTokenRoute,
  RSlugRoute: RSlugRoute,
  ApiPublicCitationSweepRoute: ApiPublicCitationSweepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
